### ISSUE TITLE
lua-resty-sniproxy do not use the upstream ?

### ISSUE THREAD

**Issue by daxiong380380** [fffonion/lua-resty-sniproxy#2]
@fffonion 
Hi,
As you say,SNI Proxy based on the ngx_lua cosocket API, it means you don't use the nginx's upstream,doesn't it.
cosocket bulids the short TCP connection with the server,so its performance is a problem .

**Comment by fffonion** [comment]
That's fair point. cosocket has `setkeepalive` API that can use a connection pool to manage connections.The same connection can thus be reused if the former stream finished in clean state. In my test cases, there's always dirty state on either side of sockets so I deleted it. It would be some extra codes in `_cleanup` function to make it work properly. PR is welcomed. 😄 

Since you referenced the upstream module: buffer copying is done in lua layer in this module and is thus leading to bad performance when bandwidth is high.
The most ideal solution is to implement access_by_lua* in stream-lua-module and thus we can use proxy_pass for forwarding after intercepting tls header. Or to exposure API of ngx_stream_proxy so that we can do pipelining in lua layer.

**Comment by fffonion** [comment]
@daxiong380380 Since version 0.20, when used with OpenResty >= 1.13.6.1 with preread API supported, this library can use the nginx proxying. Please see readme for an updated configuration.

Consider this ticket as obsoleted, feel free to open a new issue if you found any question. Thank you!
